appname="网易云音乐下载器"
appver="1.1"
appcode="1"
appsdk="15"
path_pattern=""
packagename="com.lanceliang.neteast"
theme="Theme"
app_key=""
app_channel=""
developer=""
description=""
debugmode=true
user_permission={
  "INTERNET",
  "WRITE_EXTERNAL_STORAGE"
}
